[phases.setup]
nixPkgs = ["jdk17", "nodejs"]

[phases.build]
cmds = ["cd backend && chmod +x mvnw && ./mvnw clean package -DskipTests"]

[start]
cmd = "java -Dserver.port=$PORT -jar backend/target/EventBookingBackend.jar"
