version: 1
services:
  - type: web
    name: event-booking-backend
    env: java
    region: singapore
    plan: free
    buildCommand: cd backend && mvn clean package -DskipTests
    startCommand: cd backend && java -Dserver.port=$PORT -jar target/EventBookingBackend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres.dlpxciimpvqugavnitne
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: APP_CORS_ALLOWED_ORIGINS
        value: https://zendrumbooking.vercel.app,http://localhost:5173,http://localhost:3000
      - key: RAZORPAY_KEY_ID
        value: rzp_test_placeholder
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: SPRING_MAIL_USERNAME
        value: eventbooking.otp@gmail.com
      - key: SPRING_MAIL_PASSWORD
        sync: false
      - key: WALLET_SERVICE_URL
        value: https://wallet-service-placeholder.onrender.com
      - key: WALLET_API_KEY
        value: sk_test_03abcd094afe7353305ec9fe8dc7907058beb9870e7981e6
      - key: WALLET_WEBHOOK_SECRET
        value: whsec_bc24cea9c3c052796686b6aa5b886109d13f85e09965540b
